### ISSUE TITLE
App not building with Xcode 12.5

### ISSUE THREAD

**Issue by thom1606** [SimonErm/react-native-job-queue#49] opened 2021-04-28 07:29 UTC
Yesterday I updated my Xcode to 12.5 and was unable to update my app.
When trying to build my app in Xcode is receive the following error:

```
Undefined symbols for architecture x86_64:
  "Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer<A>) -> (Swift.IndexingIterator<Swift._ArrayBuffer<A>>, Swift.Int)", referenced from:
      generic specialization <serialized, Swift._ArrayBuffer<Swift.Int8>> of Swift._copyCollectionToContiguousArray<A where A: Swift.Collection>(A) -> Swift.ContiguousArray<A.Element> in libreact-native-job-queue.a(SQLiteDatabase.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The project seems to build fine when `react-native-job-queue` is not added.

**Comment by projuljustin** [comment] 2021-04-29 13:15
I'm seeing the same thing

Undefined symbols for architecture x86_64:
  "Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer<A>) -> (Swift.IndexingIterator<Swift._ArrayBuffer<A>>, Swift.Int)", referenced from:
      generic specialization <serialized, Swift._ArrayBuffer<Swift.Int8>> of Swift._copyCollectionToContiguousArray<A where A: Swift.Collection>(A) -> Swift.ContiguousArray<A.Element> in libreact-native-job-queue.a(SQLiteDatabase.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by projuljustin** [comment] 2021-04-29 13:39
Tried https://github.com/danielgindi/Charts/issues/4636, but seeing more errors after that.

![image](https://user-images.githubusercontent.com/58796652/116559788-03723100-a8be-11eb-91c6-751fadbd6ccd.png)

**Comment by SimonErm** [comment] 2021-04-29 19:36
I am currently updating XCode tto reproduce this :D

**Comment by SimonErm** [comment] 2021-04-29 21:57
The build just fails because of these two sqlite method calls:

https://github.com/SimonErm/react-native-job-queue/blob/c817e6e95e6986f99bd2432285db011b61e0e7fe/ios/SQLiteDatabase.swift#L15
https://github.com/SimonErm/react-native-job-queue/blob/c817e6e95e6986f99bd2432285db011b61e0e7fe/ios/SQLiteDatabase.swift#L42

but i currently don't how i could fix this.

**Comment by projuljustin** [comment] 2021-04-29 22:13
I tried removing xCode 12.5 and installing 12.4, but I still get errors for some reason? 
![image](https://user-images.githubusercontent.com/58796652/116624782-cd589f80-a905-11eb-847c-6799d0c79207.png)

**Comment by projuljustin** [comment] 2021-04-29 22:42
Hmm that didn't seem to work either. Any ideas for just getting something working again?

**Comment by projuljustin** [comment] 2021-04-29 22:58
Oh I lied. I had removed "$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)" in my Library Search Path during some troubleshooting. Once I put that back, and using 12.4 xCode and command line tools, looks like the build is completing successfully again.

**Comment by SimonErm** [comment] 2021-04-30 20:11
https://github.com/facebook/react-native/issues/31179#issuecomment-829536845 works, but it's important to add dummy.swift file to the project and if you already have on delete it and add a new one.

**Comment by VanTigranyan** [comment] 2021-05-28 08:25
@SimonErm hey. Any plans to make a fix for this? Seems like the RN team created a patch

**Comment by VanTigranyan** [comment] 2021-05-28 10:30
For everyone that had a problem with newer RN and Xcode versions: this helped me https://github.com/facebook/react-native/issues/31179#issuecomment-829536845

**Comment by SimonErm** [comment] 2021-05-28 19:39
@VanTigranyan i am not sure if i can provide any fix for that. I think it has to be fixed in the project template and for the existing projects, the xcode setup has to be fixed.

**Comment by VanTigranyan** [comment] 2021-06-03 07:24
@SimonErm I don't think you can provide any fix for this either. Thanks for the reply.

**Closed** 2021-07-23 21:36 UTC
